#!/bin/bash

# Start all process to configure the teltonika.
# The process running in subshell.

while getopts F: options; do
   case ${options} in
      F) TELTONIKA=${OPTARG} ;;
   esac
done

declare -a RESPONSE=()

if ! [ -v TELTONIKA ] ; then
  RESPONSE+=("-F: Specifies the interfaces where teltonika is connected.")
fi

if [ ${#RESPONSE[@]} -ne 0 ] ; then
  printf '%s\n' "${RESPONSE[@]}"
  exit 1;
fi

unset RESPONSE

IFS=', ' read -r -a callinterface <<< "$TELTONIKA"

running() {
  ps aux | grep "${1%% *}" | grep -v grep > /dev/null
  [[ $? -eq 0 ]] && $1 &
  return 0
}

while sleep 4; do
  for ip in "${callinterface[@]}"; do
    process="${TOOL}/snippet -i $ip"
    running "$process"
  done 
done
